name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome

      - name: Ensure reports directory exists
        run: |
          if [ ! -d "cypress/reports" ]; then
            echo "Cypress reports directory does not exist."
            exit 1
          fi

      - name: Upload Cypress reports
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/reports